apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-cafeweb-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Release.Name }}-virtualservice
            routes:
              - primary
  selector:
    matchLabels:
      app: cafeapp
      tier: frontend
  template:
    metadata:
      labels:
        app: cafeapp
        tier: frontend
    spec:
      containers:
      - name: cafeweb
        image: {{ .Values.cafeweb.image }}:{{ .Values.cafeweb.tag }}
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: password
        volumeMounts:
        - name: app-config-volume
          mountPath: /var/www/html/getAppParameters.php
          subPath: getAppParameters.php
      volumes:
      - name: app-config-volume
        configMap:
          name: {{ .Release.Name }}-cafeweb-config
