apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-cafeweb-rollout
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cafeapp
      tier: frontend
  template:
    metadata:
      labels:
        app: cafeapp
        tier: frontend
    spec:
      containers:
      - name: cafeweb
        image: {{ .Values.cafeweb.image }}:{{ .Values.cafeweb.tag }}
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: cafeapp-argo-rollout-mysql
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: password
  strategy:
    canary:
      stableService: {{ .Release.Name }}-cafeweb-stable
      canaryService: {{ .Release.Name }}-cafeweb-canary
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Release.Name }}-virtualservice
            routes:
            - primary
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 100
