apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cafeweb
  labels:
    app: cafeapp
    version: {{ .Values.version }}  # Set the default to primary
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cafeapp
      tier: frontend
      version: {{ .Values.version }}  # Match the version in the selector
  template:
    metadata:
      labels:
        app: cafeapp
        tier: frontend
        version: {{ .Values.version }}  # Add the version label to the pod template
    spec:
      containers:
      - name: cafeweb
        image: {{ .Values.cafeweb.image }}:{{ .Values.cafeweb.tag }}
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: password
        volumeMounts:
        - name: app-config-volume
          mountPath: /var/www/html/getAppParameters.php
          subPath: getAppParameters.php
      volumes:
      - name: app-config-volume
        configMap:
          name: {{ .Release.Name }}-cafeweb-config

