apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
  labels:
    app: cafeapp
spec:
  capacity:
    #storage: {{ .Values.persistentVolume.size }}
    storage: null
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}

